cameraAddresses:
   - AXIS1: http:/root:pass@10.10.1.175/mjpg/1/video.mjpg
   - AXIS2: http:/root:pass@10.10.1.230/mjpg/1/video.mjpg
   - HIK1: http://admin:activeALPR@10.10.1.58/Streaming/channels/101/preview
   - TESTVIDEO: "test_clip.MOV"
