cameraAddresses:
   #- AXIS1: http:/root:pass@10.10.1.175/mjpg/1/video.mjpg
   #- AXIS2: http:/root:pass@10.10.1.230/mjpg/1/video.mjpg
   #- HIK1: http://admin:activeALPR@10.10.1.58/Streaming/channels/101/preview
   #- TESTVIDEO: "test_clip.MOV"
   #- HIK2: rtsp://LPRuser:ThisISfun1@10.48.140.5:554/Streaming/channels/101/
   - HIK:
        - url: rtsp://LPRuser:ThisISfun1@10.48.140.5:554/Streaming/channels/101/
        - aoi:
             - in:
                  - X: 232
                  - Y: 614
                  - W: 643
                  - H: 455
             - out:
                    - X: 900
                    - Y: 614
                    - W: 643
                    - H: 455

GUItoggle: true
GUIresolutionX: 800
GUIresolutionY: 600
